# **NumPy Slicing (1D, 2D, 3D)**

In [126]:
import numpy as np

**1D Array Slicing**

> array[start : end : step]



In [127]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr)

[10 20 30 40 50 60]


**Basic Slicing**

In [128]:
arr[1:4]    # from index 1 to 3

array([20, 30, 40])

In [129]:
arr[:3]     # from start to index 2

array([10, 20, 30])

In [130]:
arr[3:]     # from index 3 to end

array([40, 50, 60])

In [131]:
arr[:]

array([10, 20, 30, 40, 50, 60])

**Step Slicing**

In [132]:
arr[::2]    # every second element

array([10, 30, 50])

In [133]:
 # reverse array

**2D Array Slicing**

> array[row_slice, column_slice]



In [134]:
mat = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(mat)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


**Row Slicing**

In [135]:
mat[0:2, :]

array([[10, 20, 30],
       [40, 50, 60]])

In [136]:
mat[1:]

array([[40, 50, 60],
       [70, 80, 90]])

**Column Slicing**

In [137]:
mat[:, 0:2]


array([[10, 20],
       [40, 50],
       [70, 80]])

In [138]:
mat[:, 2]

array([30, 60, 90])

**Specific Block**

In [139]:
mat[0:2, 1:3]

array([[20, 30],
       [50, 60]])

**3D Array Slicing**


> cube[class][row][column]



In [140]:
cube = np.array([
    [
        [10, 20, 30],
        [40, 50, 60]
    ],
    [
        [70, 80, 90],
        [100, 110, 120]
    ]
])

print(cube)
print(cube.shape)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
(2, 2, 3)


**Slice one entire class**

In [141]:
cube[0, :, :]

array([[10, 20, 30],
       [40, 50, 60]])

**Slice Specific Rows Across Classes**

In [142]:
cube[:, 0, :]

array([[10, 20, 30],
       [70, 80, 90]])

**Slice Specific Column**

In [143]:
cube[:, :, 1]

array([[ 20,  50],
       [ 80, 110]])

**Slice Specific Block**

In [144]:
print(cube)
print("\n")
cube[0:2, 0:1, 1:3]

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]




array([[[20, 30]],

       [[80, 90]]])

In [145]:
# Question: select 50 and 110

**Fancy Indexing and Boolean Indexing**

In [146]:
M = np.arange(12).reshape(3,4)
print("M:\n", M)
print('\n')
print("row 1:", M[1])
print('\n')
idx = [0,2]
print("row 0 and row 2:\n", M[idx]) # fancy indexing

M:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


row 1: [4 5 6 7]


row 0 and row 2:
 [[ 0  1  2  3]
 [ 8  9 10 11]]


In [147]:
# Fancy Indexing
grid = np.array([['A', 'B', 'C'],
                 ['D', 'E', 'F'],
                 ['G', 'H', 'I']])

print("Original Grid:")
print(grid)

Original Grid:
[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]


In [174]:
# We want (0,0) which is 'A' and (2,2) which is 'I'
rows = [0, 2]
cols = [0, 2]

result = grid[rows, cols]
print(result)

['A' 'I']


In [176]:
# boolean indexing: select even numbers
x = np.arange(10)
print(x)
bool_x = (x % 2 == 0)
print(bool_x)
print("even numbers:", x[bool_x])

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]
even numbers: [0 2 4 6 8]


# **Array Operations**

In [177]:
a = np.array([[1., 2., 3.],
              [4., 5., 6.]])

b = np.array([[1., 2., 3.],
              [7., 8., 9.]])


In [179]:
g = a - b
g

array([[ 0.,  0.,  0.],
       [-3., -3., -3.]])

In [185]:
np.subtract(a, b)

array([[ 0.,  0.,  0.],
       [-3., -3., -3.]])

In [181]:
np.add(b, a) # or b + a

array([[ 2.,  4.,  6.],
       [11., 13., 15.]])

In [182]:
np.divide(a, b) # or a/b

array([[1.        , 1.        , 1.        ],
       [0.57142857, 0.625     , 0.66666667]])

In [190]:
np.multiply(a, b) # or a * b

array([[ 1.,  4.,  9.],
       [28., 40., 54.]])

In [193]:
np.exp(b) # Exponentiation (e^b)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [194]:
np.sqrt(b) # square root of every element of b

array([[1.        , 1.41421356, 1.73205081],
       [2.64575131, 2.82842712, 3.        ]])

In [196]:
np.sin(b) # trigonometric function (in ?)

array([[0.84147098, 0.90929743, 0.14112001],
       [0.6569866 , 0.98935825, 0.41211849]])

In [197]:
np.log(b) # natural log (base = ?)

array([[0.        , 0.69314718, 1.09861229],
       [1.94591015, 2.07944154, 2.19722458]])

**Matrix Multiplication**

In [198]:
f = np.array([[1., 2.],
              [1., 3.]])
g = np.array([[1., 2.],
              [3., 4.]])
mul = f @ g
print(mul)

[[ 7. 10.]
 [10. 14.]]


In [199]:
f = np.array([[1., 2.],
              [1., 3.]])
g = np.array([[1., 2.],
              [3., 4.]])

print(np.dot(f, g)) # mulitplies f * g

[[ 7. 10.]
 [10. 14.]]


**Comparision Operators (Element-wise Comparision)**

In [203]:
print(a)
print(b)
a == b

[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 2. 3.]
 [7. 8. 9.]]


array([[ True,  True,  True],
       [False, False, False]])

In [204]:
a < b

array([[False, False, False],
       [ True,  True,  True]])

**Aggregate Functions**

In [207]:
M = np.arange(1,13).reshape(3,4)  # 3x4
print("M:\n", M)
print("min:", M.min())
print("max:", M.max())
print("sum all:", M.sum())
# axis 0: first dimension, axis 1: second dimension and soon

M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
min: 1
max: 12
sum all: 78


In [214]:
print("sum axis=0 (per column):", M.sum(axis=0))

sum axis=0 (per column): [15 18 21 24]


In [213]:
print("sum axis=1 (per row):", M.sum(axis=1))

sum axis=1 (per row): [10 26 42]


In [216]:
print("mean:", M.mean(), "std:", M.std())
# argmin and argmax return index of smallest and largest value, not the value itself
print("argmin axis=0 (per column):", M.argmin(axis=0))
print("argmax axis=1 (per row):", M.argmax(axis=1))

mean: 6.5 std: 3.452052529534663
argmin axis=0 (per column): [0 0 0 0]
argmax axis=1 (per row): [3 3 3]


In [221]:
np.random.shuffle(M)
print(M)
print("argmin axis=0 (per column):", M.argmin(axis=0)) # min index per column
print("argmax axis=1 (per row):", M.argmax(axis=1)) # max index per row

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
argmin axis=0 (per column): [2 2 2 2]
argmax axis=1 (per row): [3 3 3]


# **Broadcasting**
NumPy automatically stretches smaller arrays so shapes match.

In [222]:
a = np.array([1, 2, 3])
b = 5  # scalar

result = a + b
print(result)  # [6 7 8]

[6 7 8]


"""
Broadcasting Rules:

Compare shapes from right to left.

Two dimensions are compatible if:

They are equal, OR

One of them is 1.

If incompatible, NumPy throws an error.
"""

In [224]:
a = np.array([[1], [2], [3]])
print(f"Matrix a: \n{a}")
print(np.shape(a))
print('\n')
# shape (3,1)


b = np.array([10, 20, 30])
print(f"Matrix b: \n{b}")
print(np.shape(b))
# shape (3,): treat as (1,3) for broadcasting

result = a + b
print("\n")
print(f"Result: \n{result}")
print(np.shape(result))
# shape(3,3)

Matrix a: 
[[1]
 [2]
 [3]]
(3, 1)


Matrix b: 
[10 20 30]
(3,)


Result: 
[[11 21 31]
 [12 22 32]
 [13 23 33]]
(3, 3)


In [226]:
a = np.array([[1,2,3],[4,5,6]])
print(f"Matrix a: \n{a}")

b = np.array([10, 20])
print(f"Matrix b: \n{b}")


result = a + b
print("\n")
print(f"Result: \n{result}")
print(np.shape(result))

Matrix a: 
[[1 2 3]
 [4 5 6]]
Matrix b: 
[10 20]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 