# **NumPy Basics and Foundation**


**What is NumPy?**

NumPy stands for Numerical Python. The NumPy library is the core library for scientific computing in Python.
<br>
It is used for:

- Fast numerical calculations

- Working with arrays

- Data science, machine learning, scientific computing

**Simple idea:**
- Python list = slow for math
- NumPy array = fast & smart

# Installing NumPy (Colab users: already installed)

pip install numpy

In [49]:
import numpy as np

# Python List vs NumPy Array

In [50]:
py_list = [1, 2, 3]
np_array = np.array([1, 2, 3])

print(py_list * 2)
print(np_array * 2)


[1, 2, 3, 1, 2, 3]
[2 4 6]


# Speed comparision of operation on python list and numpy array

In [51]:
import time

list1 = list(range(1000000))
sum = 0

# Using python list
start_time = time.time()
for num in list1:
  sum += num
end_time = time.time()

print(f"Sum of list1: {sum}")
print(f"Time taken on python list: {end_time-start_time}")

Sum of list1: 499999500000
Time taken on python list: 0.07394218444824219


In [52]:
np_array = np.array(range(1000000))

# Using numpy array
start_time = time.time()
sum = np.sum(np_array)
end_time = time.time()

print(f"Sum of np_array: {sum}")
print(f"Time taken on numpy array: {end_time-start_time}")


Sum of np_array: 499999500000
Time taken on numpy array: 0.0006427764892578125


# Creating Numpy Array

1. From Python list

In [53]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [54]:
x = [1, 2, 3]
a = np.array(x)
print(a)

[1 2 3]


2. Zero Array


In [55]:
x = np.zeros(5)
print(x) # default float

[0. 0. 0. 0. 0.]


In [56]:
x = input()
print(type(x))

<class 'str'>


In [57]:
np.zeros((3,4), dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

3. Ones Array


In [58]:
np.ones(4)

array([1., 1., 1., 1.])

In [59]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

4. Using arange()

In [60]:
np.arange(1, 10) # Like Python range() but returns an array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
r = range(1, 10)
print(r)  # range object

range(1, 10)


5. Using linspace()

In [62]:
np.linspace(2, 10, 5) # Evenly spaced values

array([ 2.,  4.,  6.,  8., 10.])

6. Using logspace()

In [63]:
np.logspace(0, 3, num=4, base=10) # Return numbers spaced evenly on a log scale.

array([   1.,   10.,  100., 1000.])

7. Using full()

In [64]:
np.full((5,2), fill_value=2, dtype=np.int32) # Generating nd array with same value

array([[2, 2],
       [2, 2],
       [2, 2],
       [2, 2],
       [2, 2]], dtype=int32)

8. Using eye

In [65]:
np.eye(3) # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# NumPy Array Attributes

In [66]:
a = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.int64)

print(a)

[[1 2 3]
 [4 5 6]]


In [67]:
print(f"Data type (dtype):       {a.dtype}")
print(f"Shape (rows, cols):     {a.shape}")
print(f"Total elements (size):  {a.size}")
print(f"Number of dimensions:   {a.ndim}")
print(f"Bytes per item:         {a.itemsize} bytes")
print(f"Total memory (nbytes):  {a.nbytes} bytes")

Data type (dtype):       int64
Shape (rows, cols):     (2, 3)
Total elements (size):  6
Number of dimensions:   2
Bytes per item:         8 bytes
Total memory (nbytes):  48 bytes


In [68]:
#Array attributes:
arr1 = np.array([.2, .3, 4.8, .4, 77, 9.1])
print(arr1)
print(arr1.dtype)

[ 0.2  0.3  4.8  0.4 77.   9.1]
float64


In [69]:
arr2 = np.array([.2, .3, 4.8, .4, 77, 9.1], dtype=np.int64)
print(arr2)
print(arr2.dtype)

[ 0  0  4  0 77  9]
int64


In [70]:
arr = np.array([1, 2, 3])
print(arr.astype(np.float64)) # next way of converting data types


[1. 2. 3.]


In [71]:
# Reshaping Arrays
arr = np.arange(16)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [72]:
arr.shape

(16,)

In [73]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# NumPy Arrays Dimensions with Indexing

**1D Array Indexing**

In [74]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


Index →   0  1  2  3  4
<br>
Value → 1  2  3  4  5

In [75]:
print(x[0])   # first value
print(x[3])   # fourth value
print(x[-1])  # last value


1
4
5


**2D Indexing**

In [76]:
class_marks = np.array(
          [[40, 50, 60],
          [70, 80, 90],
          [55, 65, 75]])

print(class_marks)

[[40 50 60]
 [70 80 90]
 [55 65 75]]


Row 0 → [40, 50, 60]
<br>
Row 1 → [70, 80, 90]
<br>
Row 2 → [55, 65, 75]
<br>
Indexing Format: **array[row_index][column_index]**

In [77]:
print(class_marks[0][0])  # Row 0, Column 0 → 40
print(class_marks[1][2])  # Row 1, Column 2 → 90
print(class_marks[2][1])  # Row 2, Column 1 → ?

40
90
65


3D Indexing

In [78]:
school_marks = np.array(
              [[[40, 50],
                [60, 70],
                [50, 60]],

              [[80, 85],
               [90, 95],
               [90, 100]]])

print(school_marks)


[[[ 40  50]
  [ 60  70]
  [ 50  60]]

 [[ 80  85]
  [ 90  95]
  [ 90 100]]]


In [79]:
school_marks.shape

(2, 3, 2)

Class 0
<br>
  Student 0 → [40, 50]
  <br>
  Student 1 → [60, 70]
  <br>
  Student 2 → [50, 60]

Class 1
<br>
  Student 0 → [80, 85]
  <br>
  Student 1 → [90, 95]
  <br>
  Student 2 → [90, 100]
<br>
Indexing: **array[class][row][column]**




In [80]:
print(school_marks[0][0][1])  # Class 0, Student 0, Subject 1 → 50
print(school_marks[1][1][0])  # Class 1, Student 1, Subject 0 → 90

50
90


In [81]:
print(school_marks[1, 2, 1])  # Class 1, Student 2, Subject 1 → 100

100


# **Randomness & Reproducibility**


In [82]:
import random

In [83]:
np.random.seed(1337) # reproducibility

np.random.randint(1,10) # Random integer from [1, 10)

8

**Different ways of creating random values**

**1) np.random.randint() → Random Integers**

In [84]:
np.random.randint(1, 7) # single value: low (inclusive) → high (exclusive)

6

In [85]:
np.random.randint(0, 100, size=5) # 1D array

array([92, 39, 89, 39, 90])

In [86]:
np.random.randint(10, 50, size=(2,3)) # 2D array

array([[28, 30, 18],
       [19, 16, 36]])

**2) np.random.rand() → Random Floats [0, 1)**
<br>
Used when:
1.   Probabilities
2.   ML weights



In [87]:
np.random.rand()        # single value

0.7328145526904823

In [88]:
np.random.rand(5)       # 1D array

array([0.11527423, 0.38627507, 0.62850118, 0.12505793, 0.98354861])

In [89]:
np.random.rand(2, 3)    # 2D array

array([[0.44322487, 0.78955834, 0.79411858],
       [0.36126157, 0.41610394, 0.58425813]])

In [90]:
np.random.random((2, 3)) # same as rand() but takes only one argument for 2D

array([[0.76017177, 0.18780841, 0.28816715],
       [0.67021886, 0.49964826, 0.17856868]])

**3) np.random.randn() → Random from Standard Normal Distribution**
<br>
Mean 0, Std Dev 1.
<br>
Values:

- Can be negative

- Mostly around 0

In [91]:
np.random.randn()

-1.3146526837845254

In [92]:
np.random.randn(5)

array([-0.37961174,  1.26521065,  0.12066774,  0.14794178, -2.75372579])

In [93]:
np.random.randn(2, 3)

array([[-0.35689632,  0.00771784,  1.47827716],
       [-0.95761463,  1.32900811, -0.98584963]])

**4) np.random.shuffle() → Shuffle In-Place**

In [94]:
arr = np.array([1,2,3,4,5])
print(arr)
np.random.shuffle(arr)
print(arr)

[1 2 3 4 5]
[3 1 2 4 5]


In [95]:
import numpy as np
import ipywidgets as widgets
from ipywidgets import interact

@interact(rows=(1,10), cols=(1,10))
def create_array(rows=3, cols=3):
    return np.random.randint(0, 100, size=(rows, cols))

interactive(children=(IntSlider(value=3, description='rows', max=10, min=1), IntSlider(value=3, description='c…

In [96]:
# Decorators: enhance the base function
import time

def timer(base_fn):
  def enhanced_fn():
    start_time = time.time()
    base_fn()
    stop_time = time.time()
    print(f"Time taken: {stop_time - start_time} seconds")
  return enhanced_fn

@timer
def brewtea():
  print("Making Tea")
  time.sleep(1)
  print("Tea is ready")

brewtea()

Making Tea
Tea is ready
Time taken: 1.0006592273712158 seconds


**Resources?**